name = "analytics-dashboard-worker"
main = "src/index.ts"
compatibility_date = "2025-03-15"

[[d1_databases]]
binding = "DB"
database_name = "analytics_dashboard_db"
database_id = "1ae258f9-b8db-46bb-8895-dcb1e59b1810"
migrations_dir = "migrations"

[vars]
TELEGRAM_CHANNEL_SLUG = "aipost"
COMPOSIO_YT_AUTH_CONFIG_ID = "ac_3OdnKMkDjn3B"
COMPOSIO_YT_ACCOUNT_ID = "ca_hNtAzNvxTYvR"
COMPOSIO_YT_CHANNEL_ID = "UCVyIOrfaZHNFWSekiu3M8Hw"
COMPOSIO_YT_ENTITY_ID = "pg-test-37d34f41-72d1-4f08-9025-f6bf44df7e08"
COMPOSIO_YT_CHANNEL_HANDLE = "irina2755"
